# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfSleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_sleep', models.DateTimeField(verbose_name='Time Of Sleep')),
                ('datetime', models.DateTimeField(verbose_name='Time when record inserted')),
                ('id_str', models.CharField(max_length=50)),
            ],
        ),
    ]
