# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_auto_20181029_1314")]

    operations = [
        migrations.AddField(
            model_name="timeofsleep",
            name="note",
            field=models.CharField(default="", max_length=500),
        )
    ]
